server:
  port: 8080
  
zuul:
  ignored-services:
    "*"
  routes:
    STORE-DATA-OVERVIEW: /overview/**
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 100000

spring:
  profiles:
    active: test            # 启用哪个配置文件
  application:
    name: store-zuul        # 应用名称
    

mybatis:
  mapper-locations:
    - classpath*:/mappers/*.xml  
  type-aliases-package: com.usys.store.zuul.dao
    
    
